app <- ShinyDriver$new("../../")
app$snapshotInit("Dosierung")

app$setInputs(New_Substanz = "Abführender Tee offizinal")
app$setInputs(New_Substanz2 = "Abführender Tee offizinal")
app$setInputs(New_Substanz3 = "Abführender Tee offizinal")
app$setInputs(WS = "ABACAVIR")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$uploadFile(`jun_and_int-file` = "Rezeptursammlung_präsi.zip")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$setInputs(inTabset = "Dosierungscheck")
app$setInputs(`dosierung-arzneitaxe` = "Alfatradiol")
app$setInputs(`dosierung-Menge_Substanz1` = 5)
app$setInputs(`dosierung-Mengeinsgesamt` = 0)
app$setInputs(`dosierung-Mengeinsgesamt` = 200)
app$snapshot()
app$setInputs(`dosierung-arzneitaxe` = "Benzocain")
app$setInputs(`dosierung-Menge_Substanz1` = character(0))
app$setInputs(`dosierung-Menge_Substanz1` = 1)
app$setInputs(`dosierung-Menge_Substanz1` = 10)
app$snapshot()
