app <- ShinyDriver$new("../../")
app$snapshotInit("Erstattungscheck_02")

app$setInputs(New_Substanz = "Abführender Tee offizinal")
app$setInputs(New_Substanz2 = "Abführender Tee offizinal")
app$setInputs(New_Substanz3 = "Abführender Tee offizinal")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$setInputs(inTabset = "Erstattungscheck")
app$setInputs(`ec-zusammensetzung_arzneitaxe` = "Abführender Tee offizinal")
app$snapshot()
