app <- ShinyDriver$new("../../")
app$snapshotInit("Hartfettmenge_08")

app$setInputs(New_Substanz = "Abführender Tee offizinal")
app$setInputs(New_Substanz2 = "Abführender Tee offizinal")
app$setInputs(New_Substanz3 = "Abführender Tee offizinal")
app$setInputs(WS = "ABACAVIR")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$uploadFile(`jun_and_int-file` = "Rezeptursammlung_präsi.zip")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$setInputs(inTabset = "Hartfettmengenrechner")
app$setInputs(`Stückanzahl` = character(0))
app$setInputs(`Stückanzahl` = 1)
app$setInputs(`Stückanzahl` = 10)
app$setInputs(Eichwert = character(0))
app$setInputs(Eichwert = 1)
app$setInputs(Eichwert = 1.9)
app$setInputs(`Überschuss` = 0)
app$setInputs(`Überschuss` = 20)
app$setInputs(WS_S = "Allantoin")
app$setInputs(weitere_Substanz = "click")
app$setInputs(Menge_Substanz1 = 0)
app$setInputs(Menge_Substanz1 = 0.03)
app$setInputs(Menge_Substanz2 = 0)
app$setInputs(Menge_Substanz2 = 0.02)
app$setInputs(weitere_Substanz2 = "click")
app$setInputs(WS_S3 = "Adipheninhydrochlorid")
app$setInputs(Menge_Substanz3 = 0)
app$setInputs(Menge_Substanz3 = 0.01)
app$setInputs(Berechnung_Menge = "click")
app$snapshot()
