app <- ShinyDriver$new("../../")
app$snapshotInit("Hartfettmenge_07")

app$setInputs(New_Substanz = "Abführender Tee offizinal")
app$setInputs(New_Substanz2 = "Abführender Tee offizinal")
app$setInputs(New_Substanz3 = "Abführender Tee offizinal")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$uploadFile(`nrf_and_int-Verdrängungsfaktoren` = "anlage-f_el2021-1_2800.pdf")
app$setInputs(inTabset = "Hartfettmengenrechner")
app$setInputs(WS_S = "Substanz nicht in Liste vorhanden")
app$setInputs(New_Substanz = "Aceton")
app$setInputs(`New_Verdrängungsfaktor` = 0.6)
app$setInputs(`Stückanzahl` = 10)
app$setInputs(Eichwert = 1.9)
app$setInputs(`Überschuss` = 20)
app$setInputs(`Substanz_hinzufügen` = "click")
app$setInputs(Menge_Substanz1 = 0.03)
app$setInputs(weitere_Substanz = "click")
app$setInputs(WS_S2 = "Substanz nicht in Liste vorhanden")
app$setInputs(New_Substanz2 = "Acetylcystein")
app$setInputs(New_Substanz2 = "")
app$setInputs(New_Substanz2 = "Acetylcystein")
app$setInputs(`New_Verdrängungsfaktor2` = 0.9)
app$setInputs(`Substanz_hinzufügen2` = "click")
app$setInputs(Menge_Substanz2 = 0.02)
app$setInputs(weitere_Substanz2 = "click")
app$setInputs(WS_S3 = "Substanz nicht in Liste vorhanden")
app$setInputs(New_Substanz3 = "Allantoin")
app$setInputs(New_Substanz3 = "Ammoniumsulfat")
app$setInputs(`New_Verdrängungsfaktor3` = 1)
app$setInputs(`Substanz_hinzufügen3` = "click")
app$snapshot()
app$setInputs(Menge_Substanz3 = 0.01)
app$snapshot()
app$setInputs(Berechnung_Menge = "click")
app$snapshot()
