app <- ShinyDriver$new("../../")
app$snapshotInit("Hartfettmenge_4_upload")

app$setInputs(New_Substanz = "Abführender Tee offizinal")
app$setInputs(New_Substanz2 = "Abführender Tee offizinal")
app$setInputs(New_Substanz3 = "Abführender Tee offizinal")
app$setInputs(WS = "ABACAVIR")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$uploadFile(`nrf_and_int-Verdrängungsfaktoren` = "anlage-f_el2021-1_2800.pdf")
app$setInputs(inTabset = "Hartfettmengenrechner")
app$setInputs(`Stückanzahl` = character(0))
app$setInputs(`Stückanzahl` = 1)
app$setInputs(`Stückanzahl` = 10)
app$setInputs(Eichwert = character(0))
app$setInputs(Eichwert = 1)
app$setInputs(Eichwert = 1.9)
app$setInputs(`Überschuss` = 0)
app$setInputs(`Überschuss` = 20)
app$setInputs(WS_S = "Adipheninhydrochlorid")
app$setInputs(WS_S = "Allantoin")
app$setInputs(Menge_Substanz1 = 0)
app$setInputs(Menge_Substanz1 = 0.03)
app$setInputs(Berechnung_Menge = "click")
app$snapshot()
