app <- ShinyDriver$new("../../")
app$snapshotInit("Hartfettmenge_berechnen_ohne_upload")

app$setInputs(New_Substanz = "Abführender Tee offizinal")
app$setInputs(New_Substanz2 = "Abführender Tee offizinal")
app$setInputs(New_Substanz3 = "Abführender Tee offizinal")
app$setInputs(WS = "ABACAVIR")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$setInputs(inTabset = "Hartfettmengenrechner")
app$setInputs(`Stückanzahl` = character(0))
app$setInputs(`Stückanzahl` = 1)
app$setInputs(`Stückanzahl` = 10)
app$setInputs(Eichwert = character(0))
app$setInputs(Eichwert = 1)
app$setInputs(Eichwert = character(0))
app$setInputs(Eichwert = 1.9)
app$setInputs(Eichwert = 1.96)
app$setInputs(`Überschuss` = 0)
app$setInputs(`Überschuss` = 30)
app$setInputs(Menge_Substanz1 = 0)
app$setInputs(Menge_Substanz1 = 0.06)
app$setInputs(weitere_Substanz = "click")
app$setInputs(Menge_Substanz2 = 0)
app$setInputs(Menge_Substanz2 = 0.03)
app$setInputs(`Stückanzahl` = 0)
app$setInputs(`Stückanzahl` = 20)
app$setInputs(Berechnung_Menge = "click")
app$snapshot()
