app <- ShinyDriver$new("../../")
app$snapshotInit("Hartfettmenge_differentVF")

app$setInputs(New_Substanz = "Abführender Tee offizinal")
app$setInputs(New_Substanz2 = "Abführender Tee offizinal")
app$setInputs(New_Substanz3 = "Abführender Tee offizinal")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$setInputs(inTabset = "Hartfettmengenrechner")
app$setInputs(`Stückanzahl` = 10)
app$setInputs(Eichwert = 1.9)
app$setInputs(`Überschuss` = 20)
app$setInputs(Vf = 0.6)
app$setInputs(Menge_Substanz1 = 0.03)
app$setInputs(weitere_Substanz = "click")
app$setInputs(Vf2 = 0.9)
app$setInputs(Menge_Substanz2 = 0.02)

app$setInputs(weitere_Substanz2 = "click")

app$setInputs(Menge_Substanz3 = 0.01)
app$setInputs(Vf3 = 1)
app$snapshot()
app$setInputs(Berechnung_Menge = "click")
app$snapshot()
