app <- ShinyDriver$new("../../")
app$snapshotInit("Rezeptursammlung_02")

app$setInputs(New_Substanz = "Abführender Tee offizinal")
app$setInputs(New_Substanz2 = "Abführender Tee offizinal")
app$setInputs(New_Substanz3 = "Abführender Tee offizinal")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$uploadFile(`jun_and_int-file` = "Rezeptursammlung_präsi.zip")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$setInputs(inTabset = "Rezepturensuche")
#app$setInputs(inTabset = "Rezeptursammlung")
app$setInputs(zusammensetzungRezep = "Erythromycin")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$snapshot()
app$setInputs(rezep_nicht_gefun = "click")
app$setInputs(`ec-zusammensetzung_arzneitaxe` = "Erythromycin")
app$setInputs(`Salbenfibel-Wirksubstanz` = "Erythromycin")
app$setInputs(`dosierung-arzneitaxe` = "Erythromycin")
app$snapshot()
