app <- ShinyDriver$new("../../")
app$snapshotInit("Rezeptursammlung_04")

app$setInputs(New_Substanz = "Abführender Tee offizinal")
app$setInputs(New_Substanz2 = "Abführender Tee offizinal")
app$setInputs(New_Substanz3 = "Abführender Tee offizinal")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$uploadFile(`jun_and_int-file` = "Rezeptursammlung_präsi.zip")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$setInputs(inTabset = "Rezeptursammlung")
app$setInputs(zusammensetzungRezep = "Borsäure")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$snapshot()
app$setInputs(bedenklich = "click")
app$snapshot()
