app <- ShinyDriver$new("../../")
app$snapshotInit("Rezeptursammlung_03")

app$setInputs(New_Substanz = "Abführender Tee offizinal")
app$setInputs(New_Substanz2 = "Abführender Tee offizinal")
app$setInputs(New_Substanz3 = "Abführender Tee offizinal")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$setInputs(inTabset = "Rezeptursammlung")
app$setInputs(zusammensetzungRezep = "Hartfett")
app$setInputs(`dosierung-arzneitaxe` = "Albendazol")
app$snapshot()
app$setInputs(rezep_nicht_gefun = "click")
app$setInputs(`ec-zusammensetzung_arzneitaxe` = "Hartfett")
app$snapshot()
app$setInputs(hartfettberechner = "click")
app$snapshot()
